apiVersion: v1
kind: Secret
metadata:
  name: example-com-tls
  namespace: default
data:
  tls.crt: {{ .Files.Get "example.chain.crt" | b64enc }}
  tls.key: {{ .Files.Get "example.key" | b64enc }}
type: kubernetes.io/tls