---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.component }}-pv
spec:
  storageClassName: slow
  capacity:
    storage: 10G
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: {{ .Values.persistentDisk }}
    fsType: ext4
